Add files via upload
In testing the scrap.py visiting URL I was consistently experiencing the error "AttributeError: 'NoneType' object has no attribute 'text'" which can come from requesting something that does not exist.  In fact however after quite a bit of time editing and reviewing the code the soup.find code was correct.  In order to get success with the scrape a long 10 second wait time was required after each URL visit.  This may be due to the website itself having delays or perhaps my home internet itself having too much delay.